In [23]:
import math

def basic_sigmoid(x):
    s = 1 / (1 + math.exp(-x))
    return s

In [5]:
import numpy as np

x = np.array([1, 2, 3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [18]:
print(x + 3);

[4 5 6]


In [25]:
def sigmoid(x):
    s = 1 / (1 + np.exp(-x))
    return s
print(x);print(sigmoid(x)); 
type(x)

[1 2 3]
[0.73105858 0.88079708 0.95257413]


numpy.ndarray